# Generated by Django 4.1.6 on 2023-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_device_id_alter_measurment_id_alter_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurment',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
