# Generated by Django 4.1.6 on 2023-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_device_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurment',
            name='valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
