# Generated by Django 4.1.6 on 2023-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_measurment_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connected',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
