# Generated by Django 4.1.6 on 2023-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_device_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
