# Generated by Django 4.1.6 on 2023-03-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_device_created_alter_measurment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
