# Generated by Django 4.1.6 on 2023-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_device_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurment',
            new_name='Measurement',
        ),
    ]
