# Generated by Django 4.1.6 on 2023-06-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_measurment_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.space'),
        ),
    ]
