# Generated by Django 4.1.6 on 2023-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_device_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastStatusTimestamp',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
