version: '3'

name: home_device_manager
services:
    frontend:
        container_name: frontend
        image: "tomcat_env"
        build:
            context: C:/Users/Billy Oiko/Documents/Programming/Docker/Tomcat
            dockerfile: Dockerfile
        environment:
            - TZ=Europe/Athens
        volumes:
            - "C:/Users/Billy Oiko/Documents/Programming/Projects/Diploma Thesis/home_device_management/Project/frontend:/usr/local/tomcat/webapps/app"
        restart: unless-stopped
        privileged: true
        networks:
            - home_network
        ports:
            - "9001:8080"

    frontend_react:
        container_name: frontend_react
        image: react_env
        build:
            context: C:/Users/Billy Oiko/Documents/Programming/Docker/React
            dockerfile: Dockerfile
        command: tail -F anything
        environment:
            - TZ=Europe/Athens
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - "C:/Users/Billy Oiko/Documents/Programming/Projects/Diploma Thesis/home_device_management/Project/react:/home/app"
        restart: unless-stopped
        privileged: true
        networks:
            - home_network
        ports:
        - "9002:3000"

networks:
    home_network:
        name: smart_home