# Generated by Django 4.1.6 on 2023-02-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('consumption', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceSpace',
            new_name='space',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.AddField(
            model_name='measurment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
    ]
